name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                pyinstaller -F -w -n JumbleSolver --add-data="words.txt:." --add-data="icon.png:." gui.py &&
                cp words.txt /dist &&
                cp icon.png /dist &&
                cd dist/ &&
                zip -r9 JumbleSolver-MacOS JumbleSolver.app/
            OUT_FILE_NAME: JumbleSolver-MacOS.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: >
                pyinstaller -F -w -n JumbleSolver --add-data="words.txt;." --add-data="icon.png;." gui.py &&
                copy words.txt .\dist &&
                copy icon.png .\dist &&
                tar -cf JumbleSolver-Windows.zip dist
            OUT_FILE_NAME: JumbleSolver-Windows.zip
            ASSET_MIME: application/zip

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with pyinstaller for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}
