name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            TARGET: MacOS
            CMD_BUILD: pyinstaller -w -n JumbleSolver-MacOS --add-data="words.txt:." --add-data="icon.png:." gui.py
            ARTIFACT_NAME: JumbleSolver-MacOS
          - os: windows-latest
            TARGET: Windows
            CMD_BUILD: pyinstaller -w -n JumbleSolver-Windows --add-data="words.txt;." --add-data="icon.png;." gui.py
            ARTIFACT_NAME: JumbleSolver-Windows

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with pyinstaller for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.ARTIFACT_NAME}}
          path: ${{github.workspace}}/dist/${{matrix.ARTIFACT_NAME}}/*

